/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";

export class Empty extends SpeakeasyBase {}

export class ListAllDrinksRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=empty" })
    empty?: Empty;
}

export class ListAllDrinksResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    @SpeakeasyMetadata({ elemType: shared.SpeakeasyDrink })
    classes?: shared.SpeakeasyDrink[];

    /**
     * An unexpected error response.
     */
    @SpeakeasyMetadata()
    rpcStatus?: shared.RpcStatus;
}
