/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DrinkDrinkType } from "./drinkdrinktype";
import { Expose } from "class-transformer";

/**
 * A drink served at the speakeasy
 */
export class SpeakeasyDrink extends SpeakeasyBase {
    /**
     * The name of the drink
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The price of the drink
     */
    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    price?: number;

    /**
     * Unique drink identifier for server requests
     */
    @SpeakeasyMetadata()
    @Expose({ name: "productCode" })
    productCode?: string;

    /**
     * The stock of the drink
     */
    @SpeakeasyMetadata()
    @Expose({ name: "stock" })
    stock?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: DrinkDrinkType;
}
