// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: speakeasy/v1/speakeasy.proto

/*
Package v1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package v1

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

var (
	filter_SpeakeasyService_ListDrinks_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_SpeakeasyService_ListDrinks_0(ctx context.Context, marshaler runtime.Marshaler, client SpeakeasyServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListDrinksRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_SpeakeasyService_ListDrinks_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.ListDrinks(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_SpeakeasyService_ListDrinks_0(ctx context.Context, marshaler runtime.Marshaler, server SpeakeasyServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListDrinksRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_SpeakeasyService_ListDrinks_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.ListDrinks(ctx, &protoReq)
	return msg, metadata, err

}

func request_SpeakeasyService_GetDrink_0(ctx context.Context, marshaler runtime.Marshaler, client SpeakeasyServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetDrinkRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["product_code"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "product_code")
	}

	protoReq.ProductCode, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "product_code", err)
	}

	msg, err := client.GetDrink(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_SpeakeasyService_GetDrink_0(ctx context.Context, marshaler runtime.Marshaler, server SpeakeasyServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetDrinkRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["product_code"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "product_code")
	}

	protoReq.ProductCode, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "product_code", err)
	}

	msg, err := server.GetDrink(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterSpeakeasyServiceHandlerServer registers the http handlers for service SpeakeasyService to "mux".
// UnaryRPC     :call SpeakeasyServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterSpeakeasyServiceHandlerFromEndpoint instead.
func RegisterSpeakeasyServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server SpeakeasyServiceServer) error {

	mux.Handle("GET", pattern_SpeakeasyService_ListDrinks_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/speakeasy.SpeakeasyService/ListDrinks", runtime.WithHTTPPathPattern("/v1/drinks"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_SpeakeasyService_ListDrinks_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_SpeakeasyService_ListDrinks_0(annotatedContext, mux, outboundMarshaler, w, req, response_SpeakeasyService_ListDrinks_0{resp}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_SpeakeasyService_GetDrink_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/speakeasy.SpeakeasyService/GetDrink", runtime.WithHTTPPathPattern("/v1/drinks/{product_code}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_SpeakeasyService_GetDrink_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_SpeakeasyService_GetDrink_0(annotatedContext, mux, outboundMarshaler, w, req, response_SpeakeasyService_GetDrink_0{resp}, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterSpeakeasyServiceHandlerFromEndpoint is same as RegisterSpeakeasyServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterSpeakeasyServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterSpeakeasyServiceHandler(ctx, mux, conn)
}

// RegisterSpeakeasyServiceHandler registers the http handlers for service SpeakeasyService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterSpeakeasyServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterSpeakeasyServiceHandlerClient(ctx, mux, NewSpeakeasyServiceClient(conn))
}

// RegisterSpeakeasyServiceHandlerClient registers the http handlers for service SpeakeasyService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "SpeakeasyServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "SpeakeasyServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "SpeakeasyServiceClient" to call the correct interceptors.
func RegisterSpeakeasyServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client SpeakeasyServiceClient) error {

	mux.Handle("GET", pattern_SpeakeasyService_ListDrinks_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/speakeasy.SpeakeasyService/ListDrinks", runtime.WithHTTPPathPattern("/v1/drinks"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_SpeakeasyService_ListDrinks_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_SpeakeasyService_ListDrinks_0(annotatedContext, mux, outboundMarshaler, w, req, response_SpeakeasyService_ListDrinks_0{resp}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_SpeakeasyService_GetDrink_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/speakeasy.SpeakeasyService/GetDrink", runtime.WithHTTPPathPattern("/v1/drinks/{product_code}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_SpeakeasyService_GetDrink_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_SpeakeasyService_GetDrink_0(annotatedContext, mux, outboundMarshaler, w, req, response_SpeakeasyService_GetDrink_0{resp}, mux.GetForwardResponseOptions()...)

	})

	return nil
}

type response_SpeakeasyService_ListDrinks_0 struct {
	proto.Message
}

func (m response_SpeakeasyService_ListDrinks_0) XXX_ResponseBody() interface{} {
	response := m.Message.(*ListDrinksResponse)
	return response.Drinks
}

type response_SpeakeasyService_GetDrink_0 struct {
	proto.Message
}

func (m response_SpeakeasyService_GetDrink_0) XXX_ResponseBody() interface{} {
	response := m.Message.(*GetDrinkResponse)
	return response.Drink
}

var (
	pattern_SpeakeasyService_ListDrinks_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"v1", "drinks"}, ""))

	pattern_SpeakeasyService_GetDrink_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2}, []string{"v1", "drinks", "product_code"}, ""))
)

var (
	forward_SpeakeasyService_ListDrinks_0 = runtime.ForwardResponseMessage

	forward_SpeakeasyService_GetDrink_0 = runtime.ForwardResponseMessage
)
